[build]
  command = "npm ci && npm run build && npx next export"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

## Static export does not need the Next.js plugin

## No API routes in static export



