[build]
  command = "npm run build"
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Example redirect to force https (Netlify already does this when HTTPS enforced)
#[[redirects]]
#  from = "http://greenaiautomation.ai/*"
#  to = "https://greenaiautomation.ai/:splat"
#  status = 301


