name: Lighthouse CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: npm run build || npm run export || true
      - run: npx @lhci/cli autorun --collect.staticDistDir=out || true
