name: Lighthouse CI
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start server
        run: npx next start -p 3000 --hostname 127.0.0.1 & npx wait-on http://127.0.0.1:3000

      - name: Run Lighthouse CI
        run: npx @lhci/cli autorun --config=./lighthouserc.json

      - name: Upload LHCI results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci


