name: Notion Sync
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: node scripts/sync-notion.mjs
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ARTICLES: ${{ secrets.NOTION_DB_ARTICLES }}
          NOTION_DB_CASES: ${{ secrets.NOTION_DB_CASES }}
      - name: Commit changes
        run: |
          git config user.name "gaia-bot"
          git config user.email "bot@greenaiautomation.ai"
          git add -A
          git diff --cached --quiet || git commit -m "chore: sync notion content"
          git push

name: Notion Sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (ci)
        run: npm ci

      - name: Run sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ARTICLES: ${{ secrets.NOTION_DB_ARTICLES }}
          NOTION_DB_CASES: ${{ secrets.NOTION_DB_CASES }}
        run: node scripts/sync-notion.mjs

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "gaia-bot"
          git config user.email "gaia-bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: notion sync"
            git push
          fi


